#!/usr/bin/env bash

DEVSKI_ROOT="${HOME}/.devski"
ENABLED_PATH="${DEVSKI_ROOT}/nginx/sites-available"

{ for path in ${ENABLED_PATH//:/$'\n'}; do
    for vhost in "${path}/"*; do
      vhost="${vhost##*sites-available/}"
      echo ${vhost%.conf}
    done
  done
} | sort | uniq
