#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "Not enough arguments supplied"
    echo "See:"
    echo "  devski help cat (or not)"
    exit 1
fi

SERVER_NAME=$1

DEVSKI_ROOT="${HOME}/.devski"
SERVER_CONF_FILE="${DEVSKI_ROOT}/nginx/sites-available/$SERVER_NAME.conf"

cat $SERVER_CONF_FILE
