#!/usr/bin/env bash

SERVER_NAME=$1

sudo ln -s /usr/local/etc/nginx/sites-available/$SERVER_NAME.conf /usr/local/etc/nginx/sites-enabled/$SERVER_NAME.conf

sudo launchctl stop devksi.mynameisrufus.nginx
sudo launchctl start devksi.mynameisrufus.nginx
