#!/usr/bin/env bash

FILE="/tmp/out.$$"
GREP="/bin/grep"

if [[ $EUID -ne 0 ]]; then
   echo "This command must be run as root" 1>&2
   exit 1
fi

SERVER_NAME=$1

ln -s /usr/local/etc/nginx/sites-available/$SERVER_NAME.conf /usr/local/etc/nginx/sites-enabled/$SERVER_NAME.conf

launchctl stop devksi.mynameisrufus.nginx
launchctl start devksi.mynameisrufus.nginx
