#!/usr/bin/env bash

case "$1" in
"") echo "usage: devski <command> [<args>]

Some useful devski commands are:
   commands      List all devski commands
   enable        Enable a vhost
   disable       Disable a vhost
   remove        Remove a vhost configuration
   add           Add a new vhost configuration
   templates     List vhost templates
   enabled       List enabled vhosts
   disabled      List disabled vhosts

See 'devski help <command>' for information on a specific command."
;;
enable) echo "usage: devski enable <name>

Symlinks the vhost from \`sites-available' to \`sites-enabled' and restarts
nginx."
;;
disable) echo "usage: devski disable <name>

Removes the symlink from \`sites-enabled' and restarts nginx."
;;
add) echo "usage: devski add <name> <template> [<path>]

Creates a new disabled vhost configuration using the current directory unless
\`path' has been specified."
;;
commands) echo "usage: devski commands
       devski commands --sh
       devski commands --no-sh

List all devski commands."
;;
*)
  command_path="$(command -v "devski-$1" || true)"
  if [ -n "$command_path" ]; then
    echo "Sorry, the \`$1' command isn't documented yet."
    echo
    echo "You can view the command's source here:"
    echo "$command_path"
    echo
  else
    echo "devski: no such command \`$1'"
  fi
esac

