#!/usr/bin/env bash

if [ $# -lt 2 ]; then
    echo "Not enough arguments supplied"
    echo "See:"
    echo "  devski help add"
    exit 1
fi

FILE="/tmp/out.$$"
GREP="/bin/grep"

DEVSKI_ROOT="${HOME}/.devski"
TEMPLATE_PATH="${DEVSKI_ROOT}/vhosts"
POSTCONF_PATH="${DEVSKI_ROOT}/postconf"

CURRENT=`pwd`
BASENAME=`basename $CURRENT`
TEMPLATE_NAME=$2
SERVER_NAME=$1

if [ $3 ]; then APP_PATH=$3; else APP_PATH=$CURRENT; fi

SERVER_CONF=`${TEMPLATE_PATH}/${TEMPLATE_NAME} ${SERVER_NAME} ${APP_PATH%/}`
POSTCONF=`${POSTCONF_PATH}/${TEMPLATE_NAME} ${SERVER_NAME} ${APP_PATH%/}`

SERVER_CONF_FILE="$DEVSKI_ROOT/nginx/sites-available/$SERVER_NAME.conf"
echo "$SERVER_CONF" > "$SERVER_CONF_FILE"

devski enable $SERVER_NAME

echo ""
echo "$SERVER_NAME should be running at:"
echo "  http://$SERVER_NAME.dev"
echo ""

echo "$POSTCONF"
echo ""
