#!/usr/bin/env bash

if [ $# -lt 2 ]; then
    echo "Not enough arguments supplied"
    echo "See:"
    echo "  devski help add"
    exit 1
fi

FILE="/tmp/out.$$"
GREP="/bin/grep"

DEVSKI_ROOT="${HOME}/.devski"
TEMPLATE_PATH="${DEVSKI_ROOT}/vhosts"
POSTCONF_PATH="${DEVSKI_ROOT}/postconf"
CERTS_PATH="${DEVSKI_ROOT}/nginx/certs"

CURRENT=`pwd`
BASENAME=`basename $CURRENT`
APP_PATH=$CURRENT
SERVER_PORT="8181"

while getopts ":p:d:" opt; do
  case $opt in
    p)
      SERVER_PORT=${OPTARG}
      ;;
    d)
      APP_PATH=${OPTARG}
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

SERVER_NAME=${@:$OPTIND:1}
TEMPLATE_NAME=${@:$OPTIND+1:1}

SERVER_CONF=`${TEMPLATE_PATH}/${TEMPLATE_NAME} ${SERVER_NAME} ${SERVER_PORT} ${APP_PATH%/}`
POSTCONF=`${POSTCONF_PATH}/${TEMPLATE_NAME} ${SERVER_NAME} ${SERVER_PORT} ${APP_PATH%/}`

SERVER_CONF_FILE="$DEVSKI_ROOT/nginx/sites-available/$SERVER_NAME.conf"
echo "$SERVER_CONF" > "$SERVER_CONF_FILE"

devski cert $SERVER_NAME

sudo security add-trusted-cert \
  -d -r trustRoot -k \
  "/Library/Keychains/System.keychain" "$CERTS_PATH/$SERVER_NAME.crt"

devski enable $SERVER_NAME

echo ""
echo "$SERVER_NAME should be running at:"
echo "  http://$SERVER_NAME.dev"
echo ""

echo "$POSTCONF"
echo ""
