#!/usr/bin/env bash

FILE="/tmp/out.$$"
GREP="/bin/grep"

if [[ $EUID -ne 0 ]]; then
   echo "This command must be run as root" 1>&2
   exit 1
fi

DEVSKI_ROOT="${HOME}/.devski"
NGINX_ROOT="/opt/boxen/config/nginx/"

# Generate SSL certs for https.
# http://wiki.nginx.org/HttpSslModule
#
# openssl genrsa -des3 -out dev.key 1024
# openssl req -new -key dev.key -out dev.csr
# cp dev.key dev.key.org
# openssl rsa -in dev.key.org -out dev.key
# openssl x509 -req -days 365 -in dev.csr -signkey dev.key -out dev.crt

ln -s $DEVSKI_ROOT/nginx/certs $NGINX_ROOT/certs

ln -s $DEVSKI_ROOT/nginx/sites-available $NGINX_ROOT/sites-available

ln -s $DEVSKI_ROOT/nginx/sites-enabled $NGINX_ROOT/sites-enabled

# Symlink nginx.conf
mv $NGINX_ROOT/nginx.conf $NGINX_ROOT/nginx.conf.old

ln -s $DEVSKI_ROOT/nginx/nginx.conf $NGINX_ROOT/nginx.conf
