#!/usr/bin/env bash

BOXEN_NGINX_SITES="/usr/loca/etc/nginx/servers"
DEVSKI_ROOT="${HOME}/.devski"

rm -rf ${BOXEN_NGINX_SITES}
ln -s ${DEVSKI_ROOT}/nginx/sites-enabled ${BOXEN_NGINX_SITES}

echo ""
echo "VHosts linked"
echo ""

devski reload
